CREATE TABLE IF NOT EXISTS products (
  ID SERIAL PRIMARY KEY,
  BRAND VARCHAR(25),
  MODEL VARCHAR(25),
  NAME VARCHAR(25),
  IMGURL TEXT,
  GENDER TEXT,
  PRICE INT,
  COLOR VARCHAR(50),
  SIZE INT
)